#! /bin/bash

CONTAINER_NAME="deb-pkg"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
    docker kill $CONTAINER_NAME
    docker rm $CONTAINER_NAME
fi
docker run -i --name deb-pkg -v $RECCE7_BUILD_DIR:/code/recce7 -v $DEBIAN_INSTALL_LOC:/build local/deb-pkg

