#! /bin/bash

CONTAINER_NAME="grafana"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi

cd ../debian/
./run

docker run -d -v $GRAFANA_BUILD_DIR/persisted/data/whisper:/opt/graphite/storage/whisper -v $GRAFANA_BUILD_DIR/persisted/data/elasticsearch:/var/lib/elasticsearch  -v $GRAFANA_BUILD_DIR/persisted/data/grafana:/opt/grafana/data -v $GRAFANA_BUILD_DIR/persisted/log/graphite:/opt/graphite/storage/log -v $GRAFANA_BUILD_DIR/persisted/log/elasticsearch:/var/log/elasticsearch -p 8085:8085 -p 81:81 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 --link deb-install:deb-install --name $CONTAINER_NAME local/grafana
