FROM debian

MAINTAINER Jesse Nelson <jnels1242012@gmail.com>

RUN mkdir -p /etc/recce7/plugins /etc/recce7/configs

RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install man
RUN apt-get -y install python3.4
CMD ["/bin/bash"]